# Generated by Django 4.1.5 on 2024-02-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_predmeta', models.CharField(max_length=255)),
                ('godina', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=100)),
                ('godina', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_smera', models.CharField(max_length=255)),
                ('smerovi_predmeta', models.ManyToManyField(blank=True, related_name='smerovi_predmeta', to='topics.predmeti')),
                ('smerovi_profesora', models.ManyToManyField(blank=True, related_name='smerovi_profesora', to='topics.profesori')),
            ],
        ),
        migrations.AddField(
            model_name='profesori',
            name='smer',
            field=models.ManyToManyField(blank=True, to='topics.smer'),
        ),
        migrations.AddField(
            model_name='predmeti',
            name='smer',
            field=models.ManyToManyField(blank=True, to='topics.smer'),
        ),
    ]
