# Generated by Django 5.0.1 on 2024-01-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
    ]
