# Generated by Django 5.0.1 on 2024-01-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anketa', '0002_delete_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opis_ankete', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(verbose_name='date-published')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
