# Generated by Django 5.0.1 on 2024-01-30 14:47

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='naziv',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='BackUpKod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_value', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=4)])),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_duration', models.DurationField(blank=True, default=datetime.timedelta(days=15), null=True)),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa.anketa')),
            ],
        ),
    ]
