# Generated by Django 5.0.1 on 2024-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0004_anketa_naziv_alter_anketa_publish_date_backupkod'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='broj_kodova',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='naziv',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
