# Generated by Django 5.0.1 on 2024-02-07 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0006_vezapredmeti_vezaprofesori_vezasmer'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VezaPredmeti',
        ),
        migrations.DeleteModel(
            name='VezaProfesori',
        ),
        migrations.AddField(
            model_name='anketa',
            name='smer',
            field=models.CharField(choices=[('INF', 'Informatika'), ('DRS', 'Drumski Saobracaj'), ('PRI', 'Privredno Inzinjerstvo')], default='INF', max_length=3),
        ),
        migrations.AddField(
            model_name='vezasmer',
            name='anketa',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='anketa.anketa'),
        ),
        migrations.AddField(
            model_name='vezasmer',
            name='smer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topics.smer'),
            preserve_default=False,
        ),
    ]
