# Generated by Django 5.0.1 on 2024-02-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0007_delete_vezapredmeti_delete_vezaprofesori_anketa_smer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vezasmer',
            name='anketa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anketa.anketa'),
        ),
    ]
