# Generated by Django 5.0.1 on 2024-02-08 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0008_dodajemsmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='smer',
            field=models.CharField(choices=[('1', 'Informatika'), ('2', 'Drumski Saobracaj'), ('3', 'Privredno Inzinjerstvo')], default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='vezasmer',
            name='anketa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa.anketa'),
        ),
    ]
