# Generated by Django 5.0.1 on 2024-02-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0009_promena_inicijala_u_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='smer',
            field=models.IntegerField(choices=[('1', 'Informatika'), ('2', 'Drumski Saobracaj'), ('3', 'Privredno Inzinjerstvo')], default='1'),
        ),
    ]
