# Generated by Django 5.0.1 on 2024-02-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0010_promena_izchar_u_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='smer',
            field=models.IntegerField(choices=[('Informatika', 'Informatika'), ('Drumski Saobracaj', 'Drumski Saobracaj'), ('Privredno Inzinjerstvo', 'Privredno Inzinjerstvo')], default='Informatika'),
        ),
    ]
