# Generated by Django 5.0.1 on 2024-02-11 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0013_dodajem_profesore_smerove_godinu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='godina',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
