# Generated by Django 4.1.5 on 2024-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0014_dodato_min_value_za_godinu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='smer',
            field=models.CharField(choices=[('Informatika', 'Informatika'), ('Drumski Saobracaj', 'Drumski Saobracaj'), ('Privredno Inzinjerstvo', 'Privredno Inzinjerstvo')], default='Informatika', max_length=255),
        ),
    ]
