# Generated by Django 4.1.5 on 2024-02-16 17:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0016_pitanja'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='broj_pitanja',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='anketa',
            name='vreme_do',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
