# Generated by Django 4.1.5 on 2024-02-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0017_anketa_broj_pitanja_anketa_vreme_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitanja',
            name='id',
        ),
        migrations.AlterField(
            model_name='pitanja',
            name='redni_broj',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
