# Generated by Django 4.1.5 on 2024-02-17 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0018_remove_pitanja_id_alter_pitanja_redni_broj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitanja',
            old_name='redni_broj',
            new_name='id',
        ),
    ]
