# Generated by Django 4.1.5 on 2024-02-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0019_rename_redni_broj_pitanja_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanja',
            name='redni_broj',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pitanja',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
