# Generated by Django 4.1.5 on 2024-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0021_izbori'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='aktivnost',
            field=models.BooleanField(default=False),
        ),
    ]
