# Generated by Django 5.0.1 on 2024-03-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0022_anketa_aktivnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='izbori',
            name='kod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.backupkod'),
        ),
        migrations.AlterField(
            model_name='izbori',
            name='votes',
            field=models.IntegerField(choices=[(1, 'Nisam zadovoljan'), (2, 'Onako'), (3, 'Zadovoljan'), (4, 'Odlično')], default=3),
        ),
    ]
