# Generated by Django 5.0.1 on 2024-03-02 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0024_remove_izbori_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='izbori',
            name='kod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.backupkod'),
        ),
    ]
