# Generated by Django 5.0.1 on 2024-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0026_remove_izbori_kod_remove_izbori_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='votes',
            field=models.IntegerField(choices=[(1, 'Nisam zadovoljan'), (2, 'Onako'), (3, 'Zadovoljan'), (4, 'Odlično')], default='3'),
        ),
    ]
